import { Outfit, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar/Navbar";

const outfit = Outfit({
  subsets: ["latin"],
});


export const metadata = {
  title: "Our Pixo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${outfit.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>       
        <main>
          {children}
        </main>

      </body>
    </html>
  );
}
